patreon: LaksCastro
custom: https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=lakscastro336@gmail.com&lc=GB&item_name=Do%20you%20like%20my%20job%3F%20Consider%20buying%20me%20a%20cup%20of%20chocolate%20%3DD&currency_code=GBP&no_note=0&bn=PP-DonationsBF:btn_donateCC_LG.gif:NonHostedGuest
